spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=edu
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 123456
server:
  port: 80
#logging:
 # level.com.lab.edu.mapper: debug